export const labels2 = {
  en: {
    header: "Temple Services",
    body: "We offer the following services through chatbot. Please select an option:",
    footer: "Select an option below",
    btn: "Choose an option",
    options: [
      { id: "sugam_darshan", title: "Sugam Darshan" },
      { id: "pooja_booking", title: "Puja Booking" },
      { id: "making_donation", title: "Making Donation" },
      { id: "about_temple", title: "About the Temple" },
      { id: "temple_timing", title: "Temple Timing" },
      { id: "how_to_reach", title: "How to Reach" },
      { id: "foreign_oci", title: "Foreign / OCI" },
      { id: "temple_helpdesk", title: "Temple Helpdesk" },
      { id: "temple_facilities", title: "Temple Facilities" },
      { id: "souvenir", title: "Souvenir" },
    ],
  },
  hi: {
    header: "मंदिर सेवाएँ",
    body: "हम चैटबोट के माध्यम से निम्नलिखित सेवाएँ प्रदान करते हैं। कृपया एक विकल्प चुनें:",
    footer: "नीचे एक विकल्प चुनें",
    btn: "एक विकल्प चुनें",
    options: [
      { id: "sugam_darshan", title: "सुगम दर्शन" },
      { id: "pooja_booking", title: "पूजा बुकिंग" },
      { id: "making_donation", title: "दान करना" },
      { id: "about_temple", title: "मंदिर के बारे में" },
      { id: "temple_timing", title: "मंदिर समय" },
      { id: "how_to_reach", title: "कैसे पहुँचे" },
      { id: "foreign_oci", title: "विदेशी / ओसीआई" },
      { id: "temple_helpdesk", title: "मंदिर सहायता डेस्क" },
      { id: "temple_facilities", title: "मंदिर सुविधाएं" },
      { id: "souvenir", title: "स्मारिका" },
    ],
  },
  // Repeat for other languages as needed
  ta: {
    header: "கோவில் சேவைகள்",
    body: "நாங்கள் சோட்போட் மூலம் பின்வரும் சேவைகளை வழங்குகிறோம். ஒரு விருப்பத்தை தேர்வு செய்யவும்:",
    footer: "கீழே உள்ள விருப்பத்தைத் தேர்வு செய்யவும்",
    btn: "தேர்வு செய்யவும்",
    options: [
      { id: "sugam_darshan", title: "சுகம் தரிசனம்" },
      { id: "pooja_booking", title: "பூஜை முன்பதிவு" },
      { id: "making_donation", title: "நன்கொடை" },
      { id: "about_temple", title: "கோவில் பற்றி" },
      { id: "temple_timing", title: "கோவில் நேரம்" },
      { id: "how_to_reach", title: "எப்படி செல்லுவது" },
      { id: "foreign_oci", title: "வெளிநாட்டு / ஓசிஐ" },
      { id: "temple_helpdesk", title: "கோவில் உதவி மையம்" },
      { id: "temple_facilities", title: "கோவில் வசதிகள்" },
      { id: "souvenir", title: "சுவினீர்" },
    ],
  },
  te: {
    header: "కోఠా సేవలు",
    body: "మేము చాట్‌బాట్ ద్వారా క్రింద ఉన్న సేవలను అందిస్తున్నాము. దయచేసి ఒక ఎంపికను ఎంచుకోండి:",
    footer: "కింద ఒక ఎంపికను ఎంచుకోండి",
    btn: "ఒక ఎంపికను ఎంచుకోండి",
    options: [
      { id: "sugam_darshan", title: "సుగమ దర్షనం" },
      { id: "pooja_booking", title: "పూజా బుకింగ్" },
      { id: "making_donation", title: "దానం చేయడం" },
      { id: "about_temple", title: "దేవాలయం గురించి" },
      { id: "temple_timing", title: "దేవాలయ సమయం" },
      { id: "how_to_reach", title: "ఎలా చేరాలి" },
      { id: "foreign_oci", title: "విదేశీ / OCI" },
      { id: "temple_helpdesk", title: "దేవాలయ సహాయం" },
      { id: "temple_facilities", title: "దేవాలయ సౌకర్యాలు" },
      { id: "souvenir", title: "స్మారక చిహ్నం" },
    ],
  },
  or: {
    header: "ମନ୍ଦିର ସେବାଗୁଡିକ",
    body: "ଆମେ ଚାଟବଟ୍ ମାଧ୍ୟମରେ ନିମ୍ନଲିଖିତ ସେବାଗୁଡିକୁ ପ୍ରଦାନ କରୁଛୁ। ଦୟାକରି ଏକ ବିକଳ୍ପ ଚୟନ କରନ୍ତୁ:",
    footer: "କିଛି ବିକଳ୍ପ ଚୟନ କରନ୍ତୁ",
    btn: "ଏକ ବିକଳ୍ପ ଚୟନ କରନ୍ତୁ",
    options: [
      { id: "sugam_darshan", title: "ସୁଗମ ଦର୍ଶନ" },
      { id: "pooja_booking", title: "ପୂଜା ବୁକିଂ" },
      { id: "making_donation", title: "ଦାନ କରିବା" },
      { id: "about_temple", title: "ମନ୍ଦିର ସମ୍ବନ୍ଧରେ" },
      { id: "temple_timing", title: "ମନ୍ଦିର ସମୟ" },
      { id: "how_to_reach", title: "କେମିତି ପହଞ୍ଚିବେ" },
      { id: "foreign_oci", title: "ବିଦେଶୀ / ଓସିଆଇ" },
      { id: "temple_helpdesk", title: "ମନ୍ଦିର ସହାୟତା" },
      { id: "temple_facilities", title: "ମନ୍ଦିର ସୁବିଧା" },
      { id: "souvenir", title: "ସ୍ମାରକ" },
    ],
  },
  mr: {
    header: "मंदिर सेवा",
    body: "आम्ही चॅटबॉटद्वारे खालील सेवा प्रदान करतो. कृपया एक पर्याय निवडा:",
    footer: "खालील एक पर्याय निवडा",
    btn: "एक पर्याय निवडा",
    options: [
      { id: "sugam_darshan", title: "सुगम दर्शन" },
      { id: "pooja_booking", title: "पूजा बुकिंग" },
      { id: "making_donation", title: "देणगी देणे" },
      { id: "about_temple", title: "मंदिराबद्दल माहिती" },
      { id: "temple_timing", title: "मंदिराचे वेळापत्रक" },
      { id: "how_to_reach", title: "कसे पोहोचाल" },
      { id: "foreign_oci", title: "विदेशी / ओसीआय" },
      { id: "temple_helpdesk", title: "मंदिर मदत केंद्र" },
      { id: "temple_facilities", title: "मंदिरातील सुविधा" },
      { id: "souvenir", title: "स्मरणिका" },
    ],
  },
  kn: {
    header: "ಮಂದಿರ ಸೇವೆಗಳು",
    body: "ನಾವು ಚಾಟ್‌ಬಾಟ್ ಮೂಲಕ ಕೆಳಗಿನ ಸೇವೆಗಳನ್ನು ನೀಡುತ್ತೇವೆ. ದಯವಿಟ್ಟು ಒಂದು ಆಯ್ಕೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ:",
    footer: "ಕೆಳಗಿನ ಆಯ್ಕೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
    btn: "ಆಯ್ಕೆಯನ್ನು ಆರಿಸಿ",
    options: [
      { id: "sugam_darshan", title: "ಸುಗಮ ದರ್ಶನ" },
      { id: "pooja_booking", title: "ಪೂಜಾ ಬುಕ್ಕಿಂಗ್" },
      { id: "making_donation", title: "ದುದ್ದೀಣೆ ಮಾಡುವುದು" },
      { id: "about_temple", title: "ಮಂದಿರದ ಬಗ್ಗೆ" },
      { id: "temple_timing", title: "ಮಂದಿರದ ಸಮಯ" },
      { id: "how_to_reach", title: "ಹೇಗೆ ತಲುಪುವುದು" },
      { id: "foreign_oci", title: "ವಿದೇಶಿ / OCI" },
      { id: "temple_helpdesk", title: "ಮಂದಿರದ ಸಹಾಯಕ" },
      { id: "temple_facilities", title: "ಮಂದಿರದ ಸೌಲಭ್ಯಗಳು" },
      { id: "souvenir", title: "ಸ್ಮರಣಿಕೆ" },
    ],
  },
  pa: {
    header: "ਮੰਦਰ ਸੇਵਾਵਾਂ",
    body: "ਅਸੀਂ ਚੈਟਬੋਟ ਦੇ ਜ਼ਰੀਏ ਹੇਠਲੀਆਂ ਸੇਵਾਵਾਂ ਪ੍ਰਦਾਨ ਕਰਦੇ ਹਾਂ। ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵਿਕਲਪ ਚੁਣੋ:",
    footer: "ਹੇਠਾਂ ਇੱਕ ਵਿਕਲਪ ਚੁਣੋ",
    btn: "ਇੱਕ ਵਿਕਲਪ ਚੁਣੋ",
    options: [
      { id: "sugam_darshan", title: "ਸੁਗਮ ਦਰਸ਼ਨ" },
      { id: "pooja_booking", title: "ਪੂਜਾ ਬੁੱਕਿੰਗ" },
      { id: "making_donation", title: "ਦਾਨ ਕਰਨਾ" },
      { id: "about_temple", title: "ਮੰਦਰ ਬਾਰੇ" },
      { id: "temple_timing", title: "ਮੰਦਰ ਦਾ ਸਮਾਂ" },
      { id: "how_to_reach", title: "ਕਿਵੇਂ ਪੁੱਜਣਾ ਹੈ" },
      { id: "foreign_oci", title: "ਵਿਦੇਸ਼ੀ / OCI" },
      { id: "temple_helpdesk", title: "ਮੰਦਰ ਮਦਦ ਡੈਸਕ" },
      { id: "temple_facilities", title: "ਮੰਦਰ ਦੀਆਂ ਸਹੂਲਤਾਂ" },
      { id: "souvenir", title: "ਸਮਾਰਿਕ" },
    ],
  },
  as: {
    header: "মন্দিৰ সেৱাসমূহ",
    body: "আমাৰে চেটবটৰ জৰিয়তে তলৰ সেৱাসমূহ প্ৰদান কৰা হয়। অনুগ্ৰহ কৰি এখন বিকল্প বাছক:",
    footer: "তলত এখন বিকল্প বাছক",
    btn: "এখন বিকল্প বাছক",
    options: [
      { id: "sugam_darshan", title: "সুগম দৰ্শন" },
      { id: "pooja_booking", title: "পূজা বুকিং" },
      { id: "making_donation", title: "দান কৰা" },
      { id: "about_temple", title: "মন্দিৰ সম্পৰ্কে" },
      { id: "temple_timing", title: "মন্দিৰৰ সময়সূচী" },
      { id: "how_to_reach", title: "কিদৰে যাব" },
      { id: "foreign_oci", title: "বিদেশী / OCI" },
      { id: "temple_helpdesk", title: "মন্দিৰ সাহায্য ডেস্ক" },
      { id: "temple_facilities", title: "মন্দিৰৰ সুবিধাসমূহ" },
      { id: "souvenir", title: "স্মাৰিক" },
    ],
  },
  bn: {
    header: "মন্দির সেবা",
    body: "আমরা চ্যাটবটের মাধ্যমে নিম্নলিখিত সেবা প্রদান করি। অনুগ্রহ করে একটি বিকল্প নির্বাচন করুন:",
    footer: "নিচে একটি বিকল্প নির্বাচন করুন",
    btn: "বিকল্প নির্বাচন করুন",
    options: [
      { id: "sugam_darshan", title: "সুগম দর্শন" },
      { id: "pooja_booking", title: "পূজা বুকিং" },
      { id: "making_donation", title: "দান করা" },
      { id: "about_temple", title: "মন্দির সম্পর্কে" },
      { id: "temple_timing", title: "মন্দির সময়সূচী" },
      { id: "how_to_reach", title: "কিভাবে পৌঁছাবেন" },
      { id: "foreign_oci", title: "বিদেশী / OCI" },
      { id: "temple_helpdesk", title: "মন্দির হেল্পডেস্ক" },
      { id: "temple_facilities", title: "মন্দিরের সুবিধা" },
      { id: "souvenir", title: "স্মারক" },
    ],
  },
};
